import "../styles/globals.css";
import type { AppProps } from "next/app";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect, useState } from "react";
import { WagmiConfig, configureChains, createClient } from "wagmi";
import { publicProvider } from "wagmi/providers/public";
import { Chain } from "wagmi";
import { gnosis, gnosisChiado } from "wagmi/chains";
import Navbar from "@components/Navbar";

const theme = extendTheme({
  styles: {
    global: {
      "html,body": {
        backgroundColor: "#000113",
      },
      "*": {
        fontFamily: "DM Sans",
        color: "white",
        backgroundColor: "transparent",
      },
      button: {
        backgroundColor: "transparent !important",
        border: "1px solid gray",
        _hover: {
          border: "1px solid lightgray",
        },
      },
    },
  },
});

const { provider, webSocketProvider } = configureChains(
  [gnosis],
  [publicProvider()]
);

const client = createClient({
  autoConnect: true,
  provider,
  webSocketProvider,
});

export default function App({ Component, pageProps, router }: AppProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <WagmiConfig client={client}>
      <ChakraProvider theme={theme}>
        <Head>
          <title>Journey: Gnosis-Native Quests</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Component {...pageProps} key={router.route} />
      </ChakraProvider>
    </WagmiConfig>
  );
}
